# Generated by Django 3.1.4 on 2020-12-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imageCat',
            new_name='CatImage',
        ),
    ]
