# Generated by Django 3.1.4 on 2020-12-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_auto_20201206_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='CatImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catName',
            new_name='name',
        ),
    ]
