# Generated by Django 3.1.4 on 2020-12-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_auto_20201206_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='catname',
        ),
    ]
