# Generated by Django 3.1.4 on 2020-12-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0004_auto_20201206_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='catImage',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catname',
            new_name='catName',
        ),
    ]
