<<<<<<< HEAD
# Generated by Django 3.1.4 on 2020-12-12 13:34
=======
# Generated by Django 3.1.4 on 2020-12-12 13:02
>>>>>>> ed3321db849c312c25a9f88f4dc3f946dfb4c884

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
