# Generated by Django 3.1.4 on 2020-12-20 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceProvider', '0002_auto_20201220_2158'),
        ('User', '0002_auto_20201220_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Subject', models.CharField(max_length=2000, unique=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
