<<<<<<< HEAD
# Generated by Django 3.1.4 on 2020-12-12 13:34
=======
# Generated by Django 3.1.4 on 2020-12-12 13:02
>>>>>>> ed3321db849c312c25a9f88f4dc3f946dfb4c884

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('SubCategory', '0001_initial'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='put your name', max_length=20)),
                ('phone', models.CharField(default='0000', max_length=12)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceProviders', to='Category.category')),
            ],
        ),
    ]
