# Generated by Django 3.1.4 on 2020-12-07 09:04

from django.db import migrations, models
import django.db.models.deletion


className Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Location', '0001_initial'),
        ('SubCategory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='put your name', max_length=20)),
                ('phone', models.CharField(default='0000', max_length=12)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.area')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.city')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.URLField()),
                ('servicProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.serviceprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceProvider.serviceprovider')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SubCategory.subcategory')),
            ],
        ),
    ]
